export const HOMEPAGE_FEATURES = [
  {
    id: 'whatsapp-entry',
    icon: 'MessageCircleMore',
    title: 'WhatsApp-First Entry',
    desc: 'Start on WhatsApp, receive OTP access, and continue the same application flow on the web.',
    color: '#0d9488',
  },
  {
    id: 'multi-portal',
    icon: 'Globe',
    title: 'Multi-Service Portals',
    desc: 'Move between scholarships, benefits, documents, and verification flows from one guided workspace.',
    color: '#3b82f6',
  },
  {
    id: 'citizen-profile',
    icon: 'UserRound',
    title: 'Reusable Citizen Profile',
    desc: 'Save profile details once, track completeness, and reuse them across government forms.',
    color: '#8b5cf6',
  },
  {
    id: 'document-vault',
    icon: 'FolderLock',
    title: 'Document Vault',
    desc: 'Store PAN, Aadhaar, certificates, and marksheets behind a 4-digit passkey gate.',
    color: '#f59e0b',
  },
  {
    id: 'digilocker-ocr',
    icon: 'ScanLine',
    title: 'DigiLocker + OCR Prefill',
    desc: 'Pull document data from DigiLocker and Aadhaar OCR to reduce manual entry.',
    color: '#10b981',
  },
  {
    id: 'live-tracking',
    icon: 'Activity',
    title: 'Live Tracking Timeline',
    desc: 'Follow application progress with real-time dashboard updates instead of static status checks.',
    color: '#ec4899',
  },
  {
    id: 'credential-verification',
    icon: 'ShieldCheck',
    title: 'Credential Verification',
    desc: 'Share credential proof links and QR-based verification pages after a service is completed.',
    color: '#ef4444',
  },
  {
    id: 'bank-verification',
    icon: 'Landmark',
    title: 'Bank Verification',
    desc: 'Confirm payout-ready bank details through the NPCI verification flow.',
    color: '#6366f1',
  },
];

export const HOMEPAGE_DISCOVER_CARDS = [
  {
    id: 'track-application',
    icon: 'Search',
    title: 'Track Applications',
    desc: 'Use confirmation numbers to open the application timeline and dashboard view.',
    href: '/track-search',
    color: '#3b82f6',
    bg: '#eff6ff',
  },
  {
    id: 'pm-kisan',
    icon: 'Sprout',
    title: 'PM Kisan Status',
    desc: 'Check PM Kisan payment status from the same GovBot service surface.',
    href: '/pmkisan',
    color: '#16a34a',
    bg: '#f0fdf4',
  },
  {
    id: 'digilocker-sync',
    icon: 'Link2',
    title: 'DigiLocker Sync',
    desc: 'Connect DigiLocker to fetch documents before you begin the form flow.',
    href: '/digilocker',
    color: '#0ea5e9',
    bg: '#f0f9ff',
  },
  {
    id: 'official-analytics',
    icon: 'BarChart3',
    title: 'Admin Analytics',
    desc: 'Surface fraud, disbursement, and regional dashboards for officials on the web.',
    href: '/gov-dashboard',
    color: '#ff9933',
    bg: '#fff7ed',
  },
];

export const HERO_PRODUCT_POSITIONING = {
  kicker: 'AI citizen services platform',
  title: 'Citizen Services,',
  highlight: 'Simplified',
  description: 'Start from WhatsApp or web, build one reusable profile, secure documents, fill service forms, track status, and share verified proof across public workflows.',
  primaryCta: 'Explore Services',
  primaryHref: '/services',
  secondaryCta: 'Enter Dashboard',
  secondaryHref: '/login',
  statLabels: ['Citizens Helped', 'Services Covered', 'Portals Connected'],
};

export const HERO_SERVICE_PILLS = [
  {
    id: 'benefits',
    icon: 'Sprout',
    label: 'Benefits',
    detail: 'PM Kisan and schemes',
    color: '#16a34a',
    bg: '#f0fdf4',
  },
  {
    id: 'documents',
    icon: 'FolderLock',
    label: 'Documents',
    detail: 'Vault and DigiLocker',
    color: '#f59e0b',
    bg: '#fffbeb',
  },
  {
    id: 'verification',
    icon: 'ShieldCheck',
    label: 'Verification',
    detail: 'QR proof links',
    color: '#ef4444',
    bg: '#fef2f2',
  },
  {
    id: 'official-review',
    icon: 'BarChart3',
    label: 'Officials',
    detail: 'Dashboards and review',
    color: '#3b82f6',
    bg: '#eff6ff',
  },
];

export const HERO_CONSOLE_STEPS = [
  {
    id: 'match-service',
    icon: 'Search',
    title: 'Match service',
    detail: 'GovBot routes the citizen to the right workflow.',
    color: '#0d9488',
  },
  {
    id: 'reuse-profile',
    icon: 'UserRound',
    title: 'Reuse profile',
    detail: 'Saved details and documents prefill the request.',
    color: '#8b5cf6',
  },
  {
    id: 'secure-submit',
    icon: 'LockKeyhole',
    title: 'Secure submit',
    detail: 'Passkey and OTP protect sensitive handoffs.',
    color: '#f59e0b',
  },
  {
    id: 'share-proof',
    icon: 'QrCode',
    title: 'Share proof',
    detail: 'QR links and timelines stay available after completion.',
    color: '#3b82f6',
  },
];

export const HERO_CHAT_MESSAGES = [
  {
    id: 'citizen-whatsapp',
    channel: 'WhatsApp',
    speaker: 'Citizen',
    message: 'Hi GovBot, can I renew a certificate and check PM Kisan status?',
    meta: 'Incoming chat',
    side: 'left',
    color: '#0d9488',
  },
  {
    id: 'govbot-eligibility',
    channel: 'GovBot',
    speaker: 'Assistant',
    message: 'I found the right service. I can prefill it from your citizen profile.',
    meta: 'Service matched',
    side: 'right',
    color: '#ff9933',
  },
  {
    id: 'vault-passkey',
    channel: 'Vault',
    speaker: 'Secure docs',
    message: 'Aadhaar, PAN, and income proof are ready behind passkey.',
    meta: '4-digit lock',
    side: 'left',
    color: '#f59e0b',
  },
  {
    id: 'live-tracker',
    channel: 'Tracker',
    speaker: 'Dashboard',
    message: 'Request submitted. Timeline and proof link are live.',
    meta: 'Live status',
    side: 'right',
    color: '#3b82f6',
  },
];

export const ONBOARDING_SIGNALS = [
  {
    id: 'chat-intake',
    icon: 'MessageCircleMore',
    title: 'Chat intake',
    detail: 'WhatsApp OTP received',
    color: '#0d9488',
  },
  {
    id: 'profile-ready',
    icon: 'UserRound',
    title: 'Profile ready',
    detail: 'Reusable details checked',
    color: '#8b5cf6',
  },
  {
    id: 'vault-locked',
    icon: 'FolderLock',
    title: 'Vault locked',
    detail: 'Passkey protects docs',
    color: '#f59e0b',
  },
  {
    id: 'timeline-live',
    icon: 'Activity',
    title: 'Timeline live',
    detail: 'Status pushed to dashboard',
    color: '#3b82f6',
  },
];

export const ONBOARDING_ACTIVITY_ITEMS = [
  {
    id: 'phone-verified',
    icon: 'MessageCircleMore',
    title: 'Phone verified',
    detail: 'WhatsApp OTP confirmed',
    status: 'Live',
    color: '#0d9488',
  },
  {
    id: 'profile-attached',
    icon: 'UserRound',
    title: 'Profile attached',
    detail: 'Name, address, and family details reused',
    status: '82%',
    color: '#8b5cf6',
  },
  {
    id: 'vault-unlocked',
    icon: 'FolderLock',
    title: 'Vault unlocked',
    detail: 'Aadhaar, PAN, and certificates ready',
    status: 'Passkey',
    color: '#f59e0b',
  },
  {
    id: 'official-sync',
    icon: 'BarChart3',
    title: 'Official sync',
    detail: 'Dashboard timeline updated for review',
    status: 'Sent',
    color: '#3b82f6',
  },
];

export const SERVICE_CARDS = [
  {
    id: 'apply-scholarship',
    icon: 'GraduationCap',
    title: 'Apply for Scholarship',
    description: 'Apply to NSP, SSP, CSSS, or Minority scholarship portals',
    href: '/eligibility',
    color: '#ff9933',
    bg: '#fff7ed',
  },
  {
    id: 'track-application',
    icon: 'Search',
    title: 'Track Application',
    description: 'Track your application with confirmation number and live status updates',
    href: '/track-search',
    color: '#3b82f6',
    bg: '#eff6ff',
  },
  {
    id: 'citizen-profile',
    icon: 'User',
    title: 'Citizen Profile',
    description: 'Build your reusable profile with completeness scoring and form prefill',
    href: '/profile',
    color: '#8b5cf6',
    bg: '#f5f3ff',
  },
  {
    id: 'pm-kisan',
    icon: 'Sprout',
    title: 'PM Kisan Status',
    description: 'Check PM Kisan payment status with Aadhaar or Registration No.',
    href: '/pmkisan',
    color: '#16a34a',
    bg: '#f0fdf4',
  },
  {
    id: 'check-eligibility',
    icon: 'CheckCircle',
    title: 'Check Eligibility',
    description: 'Answer 4 quick questions to find matching scholarships',
    href: '/eligibility',
    color: '#0d9488',
    bg: '#f0fdfa',
  },
  {
    id: 'whatsapp-login',
    icon: 'MessageCircleMore',
    title: 'WhatsApp Login',
    description: 'Sign in with WhatsApp OTP or continue from the QR handoff flow',
    href: '/login',
    color: '#f59e0b',
    bg: '#fffbeb',
  },
];

export const TOOL_CARDS = [
  {
    id: 'aadhaar-ocr',
    icon: 'ScanLine',
    title: 'Aadhaar OCR',
    description: 'Upload Aadhaar photo to extract name, DOB, and identity data',
    href: '/ocr',
    requiresAuth: true,
    color: '#06b6d4',
    bg: '#ecfeff',
  },
  {
    id: 'document-vault',
    icon: 'FolderLock',
    title: 'Document Vault',
    description: 'Store and open sensitive documents behind a 4-digit passkey',
    href: '/documents',
    requiresAuth: true,
    color: '#f59e0b',
    bg: '#fffbeb',
  },
  {
    id: 'bank-verification',
    icon: 'Landmark',
    title: 'Bank Verification',
    description: 'Verify bank account details via NPCI penny drop before disbursement',
    href: '/bank-verify',
    requiresAuth: true,
    color: '#10b981',
    bg: '#ecfdf5',
  },
  {
    id: 'live-dashboard',
    icon: 'Activity',
    title: 'Live Dashboard',
    description: 'Watch realtime status updates and application activity in your dashboard',
    href: '/dashboard',
    requiresAuth: true,
    color: '#3b82f6',
    bg: '#eff6ff',
  },
  {
    id: 'credential-verification',
    icon: 'ShieldCheck',
    title: 'Credential Wallet & Verify',
    description: 'Open wallet records, proof links, and QR-based credential verification',
    href: '/wallet',
    requiresAuth: true,
    color: '#8b5cf6',
    bg: '#f5f3ff',
  },
  {
    id: 'digilocker-sync',
    icon: 'Link2',
    title: 'DigiLocker',
    description: 'Connect DigiLocker to auto-fetch documents and prefill scholarship flows',
    href: '/digilocker',
    requiresAuth: true,
    color: '#0ea5e9',
    bg: '#f0f9ff',
  },
  {
    id: 'renewal-reminders',
    icon: 'Bell',
    title: 'Renewal Reminders',
    description: 'View and register scholarship renewal reminders',
    href: '/renewals',
    requiresAuth: true,
    color: '#ef4444',
    bg: '#fef2f2',
  },
];

export const LOGIN_HIGHLIGHTS = [
  {
    id: 'whatsapp-otp',
    title: 'WhatsApp OTP sign-in',
    description: 'Receive the OTP on WhatsApp and continue into your dashboard.',
  },
  {
    id: 'qr-handoff',
    title: 'QR login handoff',
    description: 'Open the same login flow from the QR handoff generated in chat.',
  },
  {
    id: 'dashboard-access',
    title: 'Dashboard access after verification',
    description: 'Land directly in tracking, profile, documents, and wallet flows after login.',
  },
];
